[tox]
envlist = py310, py311, py312, py313, py314

[testenv]
deps =
    # Default pytest for everyone
    pytest
    pytest-cov
    pytest-html
    pytest-json-report
    # Override for 3.10
    py310: pytest==7
    # Override for 3.11
    py311: pytest==8
commands =
  pytest --cov-report=html --cov=src/pytest_flakefighters -p no:flakefighters {posargs:tests}
