[tox]
envlist = py39, py310, py311, py312, py313, py314

[testenv]
usedevelop = true
deps =
    # Default pytest for everyone
    pytest
    pytest-cov
    pytest-html
    pytest-json-report
    importlib_metadata
    # Override for 3.9
    py39: pytest==7
    py39: scikit-learn==1.6
    # Override for 3.10
    py310: pytest==7
    # Override for 3.11
    py311: pytest==8
commands =
  pytest --cov-report=html --cov=src/pytest_flakefighters -p no:flakefighters {posargs:tests}
