name: CI Tests Draft
# This duplicate ci workflow is required so the badge in the README.md is not effected by draft PRs
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.draft == true
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - python-version: "3.10"
            pytest-version: "==7"
          - python-version: "3.11"
            pytest-version: "==8"
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Override pytest version using matrix
        if: matrix.pytest-version
        run: uv pip install "pytest${{ matrix.pytest-version }}"
      - name: Test with pytest
        run: uv run --no-sync pytest -p no:flakefighters --cov=src --cov-report=xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
